# Generated by Django 2.1 on 2018-10-26 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
